custom_dictionary  =  {
               'Yel': 'yellow',
               'Ast': 'assist',
               'Player': 'full_name',
               'Name': 'full_name',
               'Born': 'date_of_birth',
               'Age': 'age',
               'Height': 'height',
               'Weight': 'weight',
               'Gls': 'goals',
               'Red': 'red',
               'pos': 'positions',
               'Seasons': 'seasons',
               'Team': 'team_name',
               'TeamName': 'team_name',
               'team': 'team_name',
               'GP': 'games_played',
               'Fouls': 'fouls',
               'Sht': 'shots',
               'ln': 'last_name',
               'fn': 'first_name',
               'seq': 'sequence_val',
               'personkey': 'person_key',
               'jersey': 'jersey',
               'midname': 'middle_name',
               'regnum': 'register_num',
               'last_team': 'last_team',
               'pos1': 'positions',
               'pos2': 'position_1',
               'hgtF': 'height_foot',
               'hgtI': 'height_inches',
               'wght': 'weight',
               'birthdate': 'date_of_birth',
               'apprvd': 'approved',
               'nickname': 'nick_name',
               'Points': 'points',
               'Min':'minutes',
               'G':'goals',
               'A':'assist',
               'S':'shots',
               'F':'fouls',
               'pending':'pending',
               'OverallPts': 'points',
               'OverallGP': 'games_played',
               'OverallP': 'games_played',
               'OverallPlayed': 'games_played',
               'OverallStreaks': 'streaks',
               'OverallW': 'wins',
               'OverallD': 'ties',
               'OverallL': 'losses',
               'OverallT': 'ties',
               'OverallGF': 'games_for',
               'OverallGA': 'games_against',
               'OverallGD': 'goal_difference',
               'HomeW': 'home_wins',
               'HomeL': 'home_losses',
               'HomeT': 'home_ties',
               'HomeD': 'home_ties',
               'HomeGF': 'home_games_for',
               'HomeGD':'home_goal_difference',
               'HomeGA': 'home_games_against',
               'HomeP':'home_games_played',
               'HomePlayed': 'home_games_played',
               'HomeStreaks': 'home_streaks',
               'HomePts': 'home_points',
               'AwayP': 'away_games_played',
               'AwayPlayed': 'away_games_played',
               'AwayStreaks': 'away_streaks',
               'AwayPts': 'away_points',
               'AwayW': 'away_wins',
               'AwayL': 'away_losses',
               'AwayT': 'away_ties',
               'AwayD':'away_ties',
               'AwayGD': 'away_goal_difference',
               'AwayGF': 'away_games_for',
               'AwayGA': 'away_games_against',
               'ID': 'team_id',
               'Tournament':'tournament',
               
}
     
