custom_dictionary  =  {
               'Yel': 'yellow',
               'Ast': 'assist',
               'Player': 'full_name',
               'Name': 'full_name',
               'Born': 'date_of_birth',
               'Age': 'age',
               'Height': 'height',
               'Weight': 'weight',
               'Gls': 'goals',
               'Red': 'red',
               'pos': 'positions',
               'Seasons': 'seasons',
               'Team': 'team_name',
               'team': 'team_name',
               'GP': 'games_played',
               'Fouls': 'fouls',
               'Sht': 'shots',
               'ln': 'last_name',
               'fn': 'first_name',
               'seq': 'sequence_val',
               'personkey': 'person_key',
               'jersey': 'jersey',
               'midname': 'middle_name',
               'regnum': 'register_num',
               'last_team': 'previous_team',
               'pos1': 'positions',
               'pos2': 'position_1',
               'hgtF': 'height_foot',
               'hgtI': 'height_inches',
               'wght': 'weight',
               'birthdate': 'date_of_birth',
               'apprvd': 'approved',
               'nickname': 'nick_name',
               'Points': 'points',
               'Min':'minutes',
               'G':'goals',
               'A':'assist',
               'S':'shots',
               'F':'fouls',
               'pending':'pending'
}
     
